import type {
  ColorLabPhoto,
  ColorLabRecipe,
  ColorLabRecipeColor,
  ColorLabRecipeSettings,
} from "../../types/color-lab";

export const COLOR_LAB_PRESETS: ColorLabRecipeColor[] = [
  {
    name: "Amber",
    border: "border-amber-500",
    bg: "bg-amber-500/10",
    text: "text-amber-400",
    hex: "#f59e0b",
  },
  {
    name: "Teal",
    border: "border-teal-500",
    bg: "bg-teal-500/10",
    text: "text-teal-400",
    hex: "#14b8a6",
  },
  {
    name: "Purple",
    border: "border-purple-500",
    bg: "bg-purple-500/10",
    text: "text-purple-400",
    hex: "#a855f7",
  },
  {
    name: "Blue",
    border: "border-blue-500",
    bg: "bg-blue-500/10",
    text: "text-blue-400",
    hex: "#3b82f6",
  },
  {
    name: "Rose",
    border: "border-rose-500",
    bg: "bg-rose-500/10",
    text: "text-rose-400",
    hex: "#f43f5e",
  },
  {
    name: "Green",
    border: "border-green-500",
    bg: "bg-green-500/10",
    text: "text-green-400",
    hex: "#22c55e",
  },
  {
    name: "Pink",
    border: "border-pink-500",
    bg: "bg-pink-500/10",
    text: "text-pink-400",
    hex: "#ec4899",
  },
  {
    name: "Orange",
    border: "border-orange-500",
    bg: "bg-orange-500/10",
    text: "text-orange-400",
    hex: "#f97316",
  },
];

export const DEFAULT_COLOR_LAB_SETTINGS: ColorLabRecipeSettings = {
  whiteBalance: "5600K",
  blackLevel: "0",
  gamma: "Movie",
  blackGamma: "Standard 0",
  knee: "Auto",
  colorMode: "Standard",
  saturation: "0",
  colorPhase: "0",
  colorDepth: { R: "0", G: "0", B: "0", C: "0", M: "0", Y: "0" },
  detail: {
    level: "0",
    mode: "Standard",
    vhBalance: "0",
    bwBalance: "Type 1",
    limit: "0",
    crispening: "0",
    hlLightDetail: "0",
  },
};

export const MOCK_COLOR_LAB_RECIPES: ColorLabRecipe[] = [
  {
    id: "1",
    name: "Kodak Portra 400",
    baseProfile: "PP8 (S-Log3)",
    author: "@sonycreator",
    tags: ["Film", "Warm", "Portrait"],
    cameraLines: ["Alpha", "FX"],
    compatibilityNotes:
      "Ổn trên Alpha full-frame và FX entry line. Ưu tiên WB cố định để giữ skin tone ổn định.",
    createdAt: "2024-01-01T00:00:00Z",
    color: COLOR_LAB_PRESETS[0],
    settings: {
      whiteBalance: "7000K, B3-M1.5",
      blackLevel: "-7",
      gamma: "Cine1",
      blackGamma: "Wide +5",
      knee: "Manual 75% +2",
      colorMode: "S-Gamut3",
      saturation: "+25",
      colorPhase: "+1",
      colorDepth: { R: "-1", G: "+1", B: "+5", C: "+4", M: "-2", Y: "+2" },
      detail: {
        level: "0",
        mode: "Manual",
        vhBalance: "+2",
        bwBalance: "Type 3",
        limit: "3",
        crispening: "7",
        hlLightDetail: "4",
      },
    },
  },
  {
    id: "2",
    name: "Cinematic Teal & Orange",
    baseProfile: "PP10 (HLG2)",
    author: "@filmmaker",
    tags: ["Cinema", "Vibrant"],
    cameraLines: ["FX", "Cinema Line"],
    compatibilityNotes:
      "Hợp cho workflow hybrid video-first, cần kiểm soát highlight sớm khi dùng HLG2.",
    createdAt: "2024-01-02T00:00:00Z",
    color: COLOR_LAB_PRESETS[1],
    settings: {
      whiteBalance: "5500K, A2",
      blackLevel: "-5",
      gamma: "HLG2",
      blackGamma: "Wide +3",
      knee: "Manual 80% +1",
      colorMode: "BT.2020",
      saturation: "+20",
      colorPhase: "+2",
      colorDepth: { R: "+3", G: "-1", B: "+2", C: "+5", M: "+1", Y: "-2" },
      detail: {
        level: "-1",
        mode: "Manual",
        vhBalance: "+1",
        bwBalance: "Type 2",
        limit: "4",
        crispening: "5",
        hlLightDetail: "3",
      },
    },
  },
  {
    id: "3",
    name: "Moody Monochrome",
    baseProfile: "PP1 (Movie)",
    author: "@streetphotog",
    tags: ["B&W", "Street", "Contrast"],
    cameraLines: ["Alpha", "ZV"],
    compatibilityNotes:
      "Dùng tốt cho body nhỏ gọn và street setup. Theo dõi noise floor khi đẩy shadow.",
    createdAt: "2024-01-03T00:00:00Z",
    color: COLOR_LAB_PRESETS[2],
    settings: {
      whiteBalance: "5000K",
      blackLevel: "-10",
      gamma: "Movie",
      blackGamma: "Narrow +7",
      knee: "Manual 70% +3",
      colorMode: "Standard",
      saturation: "-100",
      colorPhase: "0",
      colorDepth: { R: "0", G: "0", B: "0", C: "0", M: "0", Y: "0" },
      detail: {
        level: "+3",
        mode: "Manual",
        vhBalance: "0",
        bwBalance: "Type 4",
        limit: "5",
        crispening: "9",
        hlLightDetail: "6",
      },
    },
  },
];

export const SAMPLE_COLOR_LAB_PHOTOS: ColorLabPhoto[] = [
  {
    id: "1",
    recipeId: "1",
    storagePath: "seed/kodak-portra-400/01.jpg",
    sortOrder: 10,
    url: "https://images.unsplash.com/photo-1679411156707-9e97efa60381?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb255JTIwY2FtZXJhJTIwY2luZW1hdGljJTIwZmlsbSUyMHBob3RvZ3JhcGh5fGVufDF8fHx8MTc3NDU5NjU0MHww&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Cinematic — f/1.8 1/200s ISO 800",
  },
  {
    id: "2",
    recipeId: "1",
    storagePath: "seed/kodak-portra-400/02.jpg",
    sortOrder: 20,
    url: "https://images.unsplash.com/photo-1634609015895-4504cc9783fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3J0cmFpdCUyMHBob3RvZ3JhcGh5JTIwd2FybSUyMHRvbmVzfGVufDF8fHx8MTc3NDU5NjU0MXww&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Portrait — f/2.0 1/125s ISO 400",
  },
  {
    id: "3",
    recipeId: "1",
    storagePath: "seed/kodak-portra-400/03.jpg",
    sortOrder: 30,
    url: "https://images.unsplash.com/photo-1682936189834-9e03bf5a61af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHJlZXQlMjBwaG90b2dyYXBoeSUyMG1vb2R5JTIwdXJiYW58ZW58MXx8fHwxNzc0NTk2NTQxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Street — f/5.6 1/500s ISO 200",
  },
  {
    id: "4",
    recipeId: "2",
    storagePath: "seed/cinematic-teal-orange/01.jpg",
    sortOrder: 10,
    url: "https://images.unsplash.com/photo-1720709626262-34eaf9942e43?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYW5kc2NhcGUlMjBzdW5zZXQlMjBnb2xkZW4lMjBob3VyfGVufDF8fHx8MTc3NDU5NjU0M3ww&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Landscape — f/8.0 1/60s ISO 100",
  },
  {
    id: "5",
    recipeId: "2",
    storagePath: "seed/cinematic-teal-orange/02.jpg",
    sortOrder: 20,
    url: "https://images.unsplash.com/photo-1689799514792-c536a1e0759e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwZWRpdG9yaWFsJTIwc3R1ZGlvJTIwbGlnaHRpbmd8ZW58MXx8fHwxNzc0NTk2NTQzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Fashion — f/2.8 1/250s ISO 320",
  },
  {
    id: "6",
    recipeId: "2",
    storagePath: "seed/cinematic-teal-orange/03.jpg",
    sortOrder: 30,
    url: "https://images.unsplash.com/photo-1629176015166-084bf0012160?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcmNoaXRlY3R1cmUlMjBnZW9tZXRyaWMlMjBtaW5pbWFsaXN0fGVufDF8fHx8MTc3NDU5NjU0NHww&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Architecture — f/11 1/100s ISO 200",
  },
  {
    id: "7",
    recipeId: "3",
    storagePath: "seed/moody-monochrome/01.jpg",
    sortOrder: 10,
    url: "https://images.unsplash.com/photo-1612192666621-a46f074abb4d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb29kJTIwcGhvdG9ncmFwaHklMjBmbGF0JTIwbGF5JTIwYWVzdGhldGljfGVufDF8fHx8MTc3NDU5NjU0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Food — f/3.5 1/80s ISO 640",
  },
  {
    id: "8",
    recipeId: "3",
    storagePath: "seed/moody-monochrome/02.jpg",
    sortOrder: 20,
    url: "https://images.unsplash.com/photo-1666795584387-ffcddc80cfa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjBmb3Jlc3QlMjBmb2clMjBtb29keSUyMGdyZWVufGVufDF8fHx8MTc3NDU5NjU0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Forest — f/4.0 1/30s ISO 1600",
  },
  {
    id: "9",
    recipeId: "3",
    storagePath: "seed/moody-monochrome/03.jpg",
    sortOrder: 30,
    url: "https://images.unsplash.com/photo-1742045016113-6fc7b65f26fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibGFjayUyMHdoaXRlJTIwZmlsbSUyMG5vaXIlMjBkcmFtYXRpY3xlbnwxfHx8fDE3NzQ1OTY1NDd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    caption: "Noir — f/1.4 1/1000s ISO 400",
  },
];
